### ISSUE TITLE
Tambahkan setup PhpMyAdmin dan MariaDB.

### ISSUE THREAD

**Issue by BanDroid** [doublegunz/termux-php-apache2-setup#5]
Saya pakai setup ini untuk instalasi **PHP** dan **Apache2**, tapi ketika saya lakukan instalasi **phpmyadmin** dan **mariadb**, bagaimana mengatur konfigurasi **httpd.conf** agar phpmyadmin dan mariadb bisa bekerja?

Mohon maaf saya bertanya mengenai ini karena saya masih **pemula di PHP** dan membutuhkan hal ini untuk pembelajaran saya 🙏

**Comment by doublegunz** [comment]
hi @BanDroid, 
kalau `php` dan `apache2` sudah terinstall pakai setup di repo ini, bisa langsung pakai `phpmyadmin` dan `mariadb` tanpa harus edit konfigurasi `httpd.conf`.

contoh penggunaan `mariadb`-nya bisa coba baca-baca di postingan saya [di sini](https://qadrlabs.com/post/tutorial-install-mysql-di-hp-android-menggunakan-termux)

untuk penggunaan `phpmyadmin` belum sempat saya posting. mungkin akan saya coba tuliskan tahapan tutorialnya nanti.

**Comment by BanDroid** [comment]
Terimakasih mas, untuk penginstalan phpmyadmin dan mariadb, cukup seperti ini ya?

pkg install phpmyadmin mariadb

**Comment by doublegunz** [comment]
sama-sama mas...

iya cukup run command untuk proses instalasinya.

alternatifnya bisa download manual juga. tutorial tentang install dan pengaturan konfigurasi saya posting di [sini](https://qadrlabs.com/post/tutorial-install-phpmyadmin-di-hp-android-menggunakan-termux)

**Comment by BanDroid** [comment]
Terimakasih lagi mas, semoga ilmu yang mas ajarkan menjadi berkah dan kebaikan buat saya dan orang lain.
